# Generated by Django 5.1.5 on 2025-03-13 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'AuthGroup',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'AuthUser',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('Regular', 'regular'), ('Walkin', 'walkin')], default='regular', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=255)),
                ('discount_desc', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('applies_to', models.CharField(choices=[('Item', 'items'), ('Category', 'category'), ('Customer', 'customer'), ('Order', 'order')], default='all', max_length=8)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Discounts',
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'DjangoMigrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'DjangoSession',
            },
        ),
        migrations.CreateModel(
            name='Pricelists',
            fields=[
                ('pricelist_id', models.AutoField(primary_key=True, serialize=False)),
                ('pricelist_name', models.CharField(max_length=255)),
                ('pricelist_desc', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pricelists',
                'db_table': 'pricelists',
            },
        ),
        migrations.CreateModel(
            name='Purchaseorders',
            fields=[
                ('purchaseorder_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseorder_number', models.CharField(db_column='purchaseorder__number', max_length=100, unique=True)),
                ('Purchaseorders_status', models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Received', 'received'), ('Canceled', 'canceled')], default='pending', max_length=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Purchaseorders',
                'db_table': 'Purchaseorders',
            },
        ),
        migrations.CreateModel(
            name='Stockmanagement',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stockmanagement',
                'db_table': 'stockmanagement',
            },
        ),
        migrations.CreateModel(
            name='Taxconfigurations',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=255)),
                ('rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applies_to', models.CharField(choices=[('Sales', 'sales'), ('Purchase', 'purchase'), ('Both', 'both')], default='all', max_length=9)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Taxconfigurations',
                'db_table': 'taxconfigurations',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_payables', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'DjangoContentType',
                'unique_together': {('app_label', 'model')},
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.authuser')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.djangocontenttype')),
            ],
            options={
                'db_table': 'DjangoAdminLog',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.djangocontenttype')),
            ],
            options={
                'db_table': 'AuthPermission',
                'unique_together': {('content_type', 'codename')},
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('Good', 'good'), ('Service', 'service')], default='product', max_length=7)),
                ('item_desc', models.TextField(blank=True, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.categories')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.discounts')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.taxconfigurations')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Salesorders',
            fields=[
                ('sales_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_order_number', models.CharField(max_length=100, unique=True)),
                ('order_status', models.CharField(choices=[('Pending', 'pending'), ('Processed', 'processed'), ('Shipped', 'shipped'), ('Completed', 'completed'), ('Canceled', 'canceled')], default='pending', max_length=9)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.customers')),
            ],
            options={
                'verbose_name_plural': 'Salesorders',
                'db_table': 'Salesorders',
            },
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_number', models.CharField(max_length=100, unique=True)),
                ('shipments_status', models.CharField(choices=[('Shipped', 'shipped'), ('Intransit', 'intransit'), ('Delivered', 'delivered')], default='pending', max_length=9)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.salesorders')),
            ],
            options={
                'verbose_name_plural': 'Shipments',
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('stock_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('safety_stock_level', models.IntegerField()),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.items')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.stockmanagement')),
            ],
            options={
                'verbose_name_plural': 'StockItems',
                'db_table': 'stock_items',
            },
        ),
        migrations.CreateModel(
            name='Purchasereceipts',
            fields=[
                ('purchase_receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('received_quantity', models.IntegerField()),
                ('purchase_receipt_status', models.CharField(choices=[('Complete', 'complete'), ('Partial', 'partial'), ('Rejected', 'rejected')], default='pending', max_length=8)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('purchaseorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.purchaseorders')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vendors')),
            ],
            options={
                'verbose_name_plural': 'Purchasereceipts',
                'db_table': 'Purchasereceipts',
            },
        ),
        migrations.AddField(
            model_name='purchaseorders',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vendors'),
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('warehouse_location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.authuser')),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouses',
            },
        ),
        migrations.AddField(
            model_name='stockmanagement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.warehouses'),
        ),
        migrations.CreateModel(
            name='Inventoryadjustments',
            fields=[
                ('Inventoryadjustments_id', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('Addition', 'addition'), ('Deduction', 'deduction'), ('Damage', 'damage'), ('loss', 'loss')], default='increase', max_length=9)),
                ('quantity', models.IntegerField()),
                ('adjustment_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.authuser')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.items')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.warehouses')),
            ],
            options={
                'verbose_name_plural': 'Inventoryadjustments',
                'db_table': 'Inventoryadjustments',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.authgroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.authpermission')),
            ],
            options={
                'db_table': 'AuthGroupPermissions',
                'unique_together': {('group', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.authgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.authuser')),
            ],
            options={
                'db_table': 'AuthUserGroups',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.authpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.authuser')),
            ],
            options={
                'db_table': 'AuthUserUserPermissions',
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='SalesorderDiscounts',
            fields=[
                ('salesorder_discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.discounts')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.salesorders')),
            ],
            options={
                'verbose_name_plural': 'SalesorderDiscounts',
                'db_table': 'salesorder_discounts',
                'unique_together': {('sales_order', 'discount')},
            },
        ),
        migrations.CreateModel(
            name='Salesordertax',
            fields=[
                ('salesorder_tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.salesorders')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.taxconfigurations')),
            ],
            options={
                'verbose_name_plural': 'Salesordertax',
                'db_table': 'salesordertax',
                'unique_together': {('sales_order', 'tax')},
            },
        ),
    ]
