# Generated by Django 5.1.5 on 2025-05-28 13:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('delivery_charges', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'area',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bill', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('customer_type', models.CharField(choices=[('Regular', 'regular'), ('Walkin', 'walkin')], default='regular', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='discounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=255)),
                ('discount_desc', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('applies_to', models.CharField(choices=[('Item', 'items'), ('Category', 'category'), ('Customer', 'customer'), ('Order', 'order')], default='all', max_length=8)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'discounts',
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='purchase_orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_order_number', models.CharField(max_length=100, unique=True)),
                ('order_status', models.CharField(choices=[('Pending', 'pending'), ('Processed', 'processed'), ('Shipped', 'shipped'), ('Completed', 'completed'), ('Canceled', 'canceled')], default='pending', max_length=9)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'purchase_orders',
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.TextField(blank=True, null=True)),
                ('store_location', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'store',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='tax_configurations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=255)),
                ('rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applies_to', models.CharField(choices=[('Sales', 'sales'), ('Purchase', 'purchase'), ('Both', 'both')], default='sales', max_length=9)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'tax_configurations',
                'db_table': 'tax_configurations',
            },
        ),
        migrations.CreateModel(
            name='vendors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_payables', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'vendors',
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier')], default='cashier', max_length=25)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.store')),
            ],
            options={
                'db_table': 'custom_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('Good', 'good'), ('Service', 'service')], default='Good', max_length=7)),
                ('item_desc', models.TextField(blank=True, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('safety_stock_level', models.IntegerField(default=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.categories')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.discounts')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subitems', to='myapp.items')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.tax_configurations')),
            ],
            options={
                'verbose_name_plural': 'items',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='purchase_order_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_per_piece', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('price_after_discount', models.IntegerField()),
                ('tax_price', models.IntegerField()),
                ('price_after_tax', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase_orders')),
            ],
            options={
                'verbose_name_plural': 'purchase_order_detail',
                'db_table': 'purchase_order_detail',
            },
        ),
        migrations.CreateModel(
            name='purchase_order_return',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('purchase_orders', models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase_orders')),
                ('vendor', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vendors')),
            ],
            options={
                'verbose_name_plural': 'purchase_order_return',
                'db_table': 'purchase_order_return',
            },
        ),
        migrations.CreateModel(
            name='purchase_order_return_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_quantity', models.IntegerField()),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('purchase_order_detail', models.ForeignKey(blank=True, db_column='sales_order_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase_order_detail')),
                ('return_purchase', models.ForeignKey(db_column='return_purchase_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase_order_return')),
            ],
            options={
                'verbose_name_plural': 'purchase_order_return_detail',
                'db_table': 'purchase_order_return_detail',
            },
        ),
        migrations.CreateModel(
            name='sales_order_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_per_piece', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('price_after_discount', models.IntegerField()),
                ('price_after_tax', models.IntegerField()),
                ('tax_price', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
            ],
            options={
                'verbose_name_plural': 'sales_order_detail',
                'db_table': 'sales_order_details',
            },
        ),
        migrations.CreateModel(
            name='sales_order_return',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_type', models.CharField(choices=[('damage', 'damage'), ('return item', 'return'), ('loss', 'loss')], default='return', max_length=15)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customers')),
                ('sales_order_detail', models.ForeignKey(blank=True, db_column='sales_order_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sales_order_detail')),
            ],
            options={
                'verbose_name_plural': 'sales_order_return',
                'db_table': 'sales_order_return',
            },
        ),
        migrations.CreateModel(
            name='inventory_adjustments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(blank=True, choices=[('Return', 'return'), ('Damage', 'damage'), ('Loss', 'loss'), ('Unsold_items', 'unsold_items')], default='return', max_length=15, null=True)),
                ('quantity', models.IntegerField()),
                ('adjustment_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.items')),
                ('sales_order_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.sales_order_return')),
            ],
            options={
                'verbose_name_plural': 'inventory_adjustments',
                'db_table': 'inventory_adjustments',
            },
        ),
        migrations.CreateModel(
            name='sales_order_return_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_quantity', models.IntegerField()),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('return_sale', models.ForeignKey(db_column='return_sale_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.sales_order_return')),
                ('sales_order_detail', models.ForeignKey(blank=True, db_column='sales_order_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sales_order_detail')),
            ],
            options={
                'verbose_name_plural': 'sales_order_return_detail',
                'db_table': 'sales_order_return_detail',
            },
        ),
        migrations.CreateModel(
            name='sales_orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_order_number', models.CharField(max_length=100, unique=True)),
                ('order_status', models.CharField(choices=[('Pending', 'pending'), ('Shipped', 'shipped'), ('Delivered', 'delivered'), ('Canceled', 'canceled')], default='delivered', max_length=9)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.area')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.customers')),
            ],
            options={
                'verbose_name_plural': 'sales_orders',
                'db_table': 'sales_orders',
            },
        ),
        migrations.AddField(
            model_name='sales_order_return',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sales_orders'),
        ),
        migrations.AddField(
            model_name='sales_order_detail',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sales_orders'),
        ),
        migrations.CreateModel(
            name='shipments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_number', models.CharField(max_length=100, unique=True)),
                ('shipments_status', models.CharField(choices=[('Shipped', 'shipped'), ('Intransit', 'intransit'), ('Delivered', 'delivered')], default='Delivered', max_length=9)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.sales_orders')),
            ],
            options={
                'verbose_name_plural': 'shipments',
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='stock_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('safety_stock_level', models.IntegerField()),
                ('last_restocked_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_items', to='myapp.items')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.store')),
            ],
            options={
                'verbose_name_plural': 'stock_items',
                'db_table': 'stock_items',
            },
        ),
        migrations.CreateModel(
            name='request_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
            ],
            options={
                'verbose_name_plural': 'request_note',
                'db_table': 'request_note',
            },
        ),
        migrations.CreateModel(
            name='transfer_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_transferred', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('dispatched', ' Dispatched'), ('intransit', 'Intransit'), ('delivered', 'Delivered')], default='dispatched', max_length=20)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('request_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.request_note')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'transfer_note',
                'db_table': 'transfer_note',
            },
        ),
        migrations.CreateModel(
            name='receive_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_received', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
                ('transfer_note_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.transfer_note')),
            ],
            options={
                'verbose_name_plural': 'receive_note',
                'db_table': 'receive_note',
            },
        ),
        migrations.CreateModel(
            name='purchase_receipts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('received_quantity', models.IntegerField()),
                ('purchase_receipt_status', models.CharField(choices=[('Pending', 'pending'), ('Complete', 'complete'), ('Partial', 'partial'), ('Rejected', 'rejected')], default='pending', max_length=8)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.purchase_orders')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vendors')),
            ],
            options={
                'verbose_name_plural': 'purchase_receipts',
                'db_table': 'purchase_receipts',
            },
        ),
        migrations.AddField(
            model_name='purchase_orders',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vendors'),
        ),
        migrations.CreateModel(
            name='warehouses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('warehouse_location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'warehouses',
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='warehouse_stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('safety_stock_level', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses')),
            ],
            options={
                'verbose_name_plural': 'warehouse_stock',
                'db_table': 'warehouse_stock',
            },
        ),
        migrations.AddField(
            model_name='transfer_note',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses'),
        ),
        migrations.AddField(
            model_name='store',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.warehouses'),
        ),
        migrations.CreateModel(
            name='stockmanagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.warehouses')),
            ],
            options={
                'verbose_name_plural': 'stockmanagement',
                'db_table': 'stockmanagement',
            },
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_choices', models.CharField(choices=[('store', 'Store'), ('warehouse', 'Warehouse')], default='store', max_length=10)),
                ('message', models.TextField(blank=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses')),
            ],
            options={
                'verbose_name_plural': 'notification',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='sales_order_discounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.discounts')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.sales_orders')),
            ],
            options={
                'verbose_name_plural': 'sales_order_discounts',
                'db_table': 'sales_order_discounts',
                'unique_together': {('sales_order', 'discount')},
            },
        ),
        migrations.CreateModel(
            name='sales_order_tax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.sales_orders')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.tax_configurations')),
            ],
            options={
                'verbose_name_plural': 'sales_order_tax',
                'db_table': 'sales_order_tax',
                'unique_together': {('sales_order', 'tax')},
            },
        ),
    ]
