# Generated by Django 5.1.5 on 2025-04-07 12:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('delivery_charges', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Area',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('Regular', 'regular'), ('Walkin', 'walkin')], default='regular', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=255)),
                ('discount_desc', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('applies_to', models.CharField(choices=[('Item', 'items'), ('Category', 'category'), ('Customer', 'customer'), ('Order', 'order')], default='all', max_length=8)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Discounts',
                'db_table': 'discounts',
            },
        ),
        migrations.CreateModel(
            name='Purchaseorders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseorder_number', models.CharField(db_column='purchaseorder__number', max_length=100, unique=True)),
                ('Purchaseorders_status', models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Received', 'received'), ('Canceled', 'canceled')], default='pending', max_length=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Purchaseorders',
                'db_table': 'Purchaseorders',
            },
        ),
        migrations.CreateModel(
            name='Stockmanagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stockmanagement',
                'db_table': 'stockmanagement',
            },
        ),
        migrations.CreateModel(
            name='Taxconfigurations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=255)),
                ('rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applies_to', models.CharField(choices=[('Sales', 'sales'), ('Purchase', 'purchase'), ('Both', 'both')], default='all', max_length=9)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Taxconfigurations',
                'db_table': 'taxconfigurations',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_payables', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('Good', 'good'), ('Service', 'service')], default='Good', max_length=7)),
                ('item_desc', models.TextField(blank=True, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.categories')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.discounts')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subitems', to='myapp.items')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.taxconfigurations')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='salesorder_return',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('quantity_returned', models.IntegerField()),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'salesorder_return',
                'db_table': 'salesorder_return',
            },
        ),
        migrations.CreateModel(
            name='Inventoryadjustments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('Return', 'return'), ('Damage', 'damage'), ('loss', 'loss')], default='return', max_length=9)),
                ('quantity', models.IntegerField()),
                ('adjustment_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.items')),
                ('salesorder_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.salesorder_return')),
            ],
            options={
                'verbose_name_plural': 'Inventoryadjustments',
                'db_table': 'Inventoryadjustments',
            },
        ),
        migrations.CreateModel(
            name='Salesorders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_order_number', models.CharField(max_length=100, unique=True)),
                ('order_status', models.CharField(choices=[('Pending', 'pending'), ('Processed', 'processed'), ('Shipped', 'shipped'), ('Completed', 'completed'), ('Canceled', 'canceled')], default='pending', max_length=9)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.area')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.customers')),
            ],
            options={
                'verbose_name_plural': 'Salesorders',
                'db_table': 'Salesorders',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_per_piece', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('price_after_discount', models.IntegerField()),
                ('tax_price', models.IntegerField()),
                ('price_after_tax', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorders')),
            ],
            options={
                'verbose_name_plural': 'SalesOrderDetail',
                'db_table': 'salesorderdetails',
            },
        ),
        migrations.AddField(
            model_name='salesorder_return',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='sales_order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorders'),
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_number', models.CharField(max_length=100, unique=True)),
                ('shipments_status', models.CharField(choices=[('Shipped', 'shipped'), ('Intransit', 'intransit'), ('Delivered', 'delivered')], default='Intarnsit', max_length=9)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.salesorders')),
            ],
            options={
                'verbose_name_plural': 'Shipments',
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('safety_stock_level', models.IntegerField()),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_items', to='myapp.items')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.stockmanagement')),
            ],
            options={
                'verbose_name_plural': 'StockItems',
                'db_table': 'stock_items',
            },
        ),
        migrations.CreateModel(
            name='Purchasereceipts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('received_quantity', models.IntegerField()),
                ('purchase_receipt_status', models.CharField(choices=[('Complete', 'complete'), ('Partial', 'partial'), ('Rejected', 'rejected')], default='pending', max_length=8)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('purchaseorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.purchaseorders')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vendors')),
            ],
            options={
                'verbose_name_plural': 'Purchasereceipts',
                'db_table': 'Purchasereceipts',
            },
        ),
        migrations.AddField(
            model_name='purchaseorders',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.vendors'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder_return',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('quantity_returned', models.IntegerField()),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('purchaseorder_id', models.ForeignKey(db_column='purchaseorder_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorders')),
                ('vendor_id', models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.vendors')),
            ],
            options={
                'verbose_name_plural': 'PurchaseOrder_return',
                'db_table': 'PurchaseOrder_return',
            },
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('warehouse_location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouses',
            },
        ),
        migrations.AddField(
            model_name='stockmanagement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.warehouses'),
        ),
        migrations.CreateModel(
            name='SalesorderDiscounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.discounts')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.salesorders')),
            ],
            options={
                'verbose_name_plural': 'SalesorderDiscounts',
                'db_table': 'salesorder_discounts',
                'unique_together': {('sales_order', 'discount')},
            },
        ),
        migrations.CreateModel(
            name='Salesordertax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.salesorders')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.taxconfigurations')),
            ],
            options={
                'verbose_name_plural': 'Salesordertax',
                'db_table': 'salesordertax',
                'unique_together': {('sales_order', 'tax')},
            },
        ),
    ]
