# Generated by Django 5.1.5 on 2025-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_adjustments',
            name='adjustment_type',
            field=models.CharField(blank=True, choices=[('Return', 'return'), ('Damage', 'damage'), ('Loss', 'loss'), ('Unsold_items', 'unsold_items')], default='return', max_length=15, null=True),
        ),
    ]
