# Generated by Django 5.1.5 on 2025-04-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='purchaseorder_number',
            field=models.CharField(db_column='purchaseorder_number', max_length=100, unique=True),
        ),
    ]
