# Generated by Django 5.1.5 on 2025-04-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_purchaseorders_purchaseorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_return',
            name='sales_order_detail',
            field=models.ForeignKey(blank=True, db_column='sales_order_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorderdetail'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='total_bill',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder_return',
            name='purchaseorder_id',
            field=models.ForeignKey(db_column='purchaseorder_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.purchaseorders'),
        ),
    ]
