# Generated by Django 5.1.5 on 2025-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_inventory_adjustments_adjustment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_return',
            name='return_method',
            field=models.CharField(choices=[('cash', 'cash refund'), ('replace', 'inventory_replacement'), ('credit', 'vendors credit')], default='cash', max_length=15),
        ),
        migrations.AddField(
            model_name='purchase_order_return',
            name='return_type',
            field=models.CharField(choices=[('damaged', 'damaged_goods'), ('unsold', ' unsold items')], default='unsold', max_length=15),
        ),
        migrations.AddField(
            model_name='sales_order_return',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales_order_return',
            name='return_type',
            field=models.CharField(choices=[('damage', 'damage'), ('return', 'return item'), ('loss', 'loss')], default='return', max_length=15),
        ),
        migrations.AlterField(
            model_name='purchase_receipts',
            name='purchase_receipt_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Complete', 'complete'), ('Partial', 'partial'), ('Rejected', 'rejected')], default='pending', max_length=8),
        ),
    ]
