# Generated by Django 5.1.5 on 2025-04-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_salesorder_return_sales_order_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_return',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customers'),
        ),
    ]
