# Generated by Django 5.1.5 on 2025-05-28 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_receive_note_status_alter_request_note_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive_note',
            name='item',
        ),
        migrations.RemoveField(
            model_name='receive_note',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='request_note',
            name='item',
        ),
        migrations.RemoveField(
            model_name='request_note',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transfer_note',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transfer_note',
            name='quantity_transferred',
        ),
        migrations.CreateModel(
            name='receive_note_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('receive_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.receive_note')),
            ],
            options={
                'verbose_name_plural': 'receive_note_detail',
                'db_table': 'receive_note_detail',
            },
        ),
        migrations.CreateModel(
            name='request_note_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
            ],
            options={
                'verbose_name_plural': 'request_note_detail',
                'db_table': 'request_note_detail',
            },
        ),
        migrations.CreateModel(
            name='transfer_note_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
                ('transfer_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.transfer_note')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses')),
            ],
            options={
                'verbose_name_plural': 'transfer_note_detail',
                'db_table': 'transfer_note_detail',
            },
        ),
    ]
