# Generated by Django 5.1.5 on 2025-04-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_purchase_order_return_return_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_return',
            name='return_method',
        ),
        migrations.RemoveField(
            model_name='purchase_order_return',
            name='return_type',
        ),
        migrations.AddField(
            model_name='items',
            name='last_restocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='safety_stock_level',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='sales_order_return',
            name='return_type',
            field=models.CharField(choices=[('damage', 'damage'), ('return item', 'return'), ('loss', 'loss')], default='return', max_length=15),
        ),
    ]
