# Generated by Django 5.1.5 on 2025-04-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_salesorder_return_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_return',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='salesorder_return',
            name='item',
        ),
    ]
