# Generated by Django 5.1.5 on 2025-04-17 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_purchase_order_return_return_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_adjustments',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory_adjustments',
            name='sales_order_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.sales_order_return'),
        ),
    ]
