# Generated by Django 5.1.5 on 2025-05-29 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_receive_note_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.warehouses'),
        ),
    ]
