# Generated by Django 5.1.5 on 2025-04-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_salesorder_return_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_return',
            name='price_per_piece',
        ),
        migrations.RemoveField(
            model_name='salesorder_return',
            name='quantity_returned',
        ),
        migrations.RemoveField(
            model_name='salesorder_return',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='salesorder_return',
            name='user',
        ),
        migrations.AddField(
            model_name='salesorder_return',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customers'),
        ),
        migrations.CreateModel(
            name='salesorder_returndetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_quantity', models.IntegerField()),
                ('price_per_piece', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('returnsale', models.ForeignKey(db_column='returnsale_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorder_return')),
                ('sales_order_detail', models.ForeignKey(blank=True, db_column='sales_order_detail_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.salesorderdetail')),
            ],
        ),
    ]
