# Generated by Django 5.1.5 on 2025-05-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_custom_user_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_note',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses'),
        ),
    ]
