# Generated by Django 5.1.5 on 2025-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_orders',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Shipped', 'shipped'), ('Delivered', 'delivered'), ('Canceled', 'canceled')], default='pending', max_length=9),
        ),
    ]
