# Generated by Django 5.1.5 on 2025-05-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_transfer_note_warehouse_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receive_note',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='receive_note',
            old_name='transfer_note_id',
            new_name='transfer_note',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.RenameField(
            model_name='transfer_note',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.RenameField(
            model_name='warehouse_stock',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
    ]
