# Generated by Django 5.1.5 on 2025-05-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_store_id_receive_note_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouses',
            name='user',
        ),
    ]
