# Generated by Django 5.1.5 on 2025-05-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_sales_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_orders',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Shipped', 'shipped'), ('Delivered', 'delivered'), ('Canceled', 'canceled')], default='delivered', max_length=9),
        ),
    ]
