# Generated by Django 5.1.5 on 2025-05-14 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_sales_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
