# Generated by Django 5.1.5 on 2025-05-30 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_warehouses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_note_detail',
            name='store',
        ),
        migrations.RemoveField(
            model_name='transfer_note_detail',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='receive_note',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receive_note',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.warehouses'),
        ),
        migrations.AddField(
            model_name='request_note',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request_note_detail',
            name='request_note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.request_note'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer_note',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.store'),
        ),
        migrations.AlterField(
            model_name='transfer_note',
            name='status',
            field=models.CharField(choices=[('dispatched', ' Dispatched'), ('intransit', 'Intransit'), ('delivered', 'Delivered')], default='dispatched', max_length=20),
        ),
    ]
