# Generated by Django 5.1.5 on 2025-05-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_transfer_note_detail_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_note',
            name='store',
        ),
    ]
