# Generated by Django 5.1.5 on 2025-05-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_discounts_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='shipments_status',
            field=models.CharField(choices=[('Shipped', 'shipped'), ('Intransit', 'intransit'), ('Delivered', 'delivered')], default='Delivered', max_length=9),
        ),
    ]
