# Generated by Django 5.1.5 on 2025-05-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_transfer_note_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.store'),
        ),
    ]
