# Generated by Django 5.1.5 on 2025-06-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_notification_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='total_bill',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
