# Generated by Django 5.1.5 on 2025-05-15 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_shipments_shipments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_items',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.items'),
        ),
        migrations.AlterField(
            model_name='stock_items',
            name='last_restocked_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stock_items',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_items', to='myapp.stockmanagement'),
        ),
    ]
