# Generated by Django 5.1.5 on 2025-06-05 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_customers_total_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_detail',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='purchase_order_detail',
            name='price_after_discount',
        ),
        migrations.RemoveField(
            model_name='purchase_order_detail',
            name='price_after_tax',
        ),
        migrations.RemoveField(
            model_name='purchase_order_detail',
            name='price_per_piece',
        ),
        migrations.RemoveField(
            model_name='purchase_order_detail',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='purchase_order_detail',
            name='tax_price',
        ),
        migrations.RemoveField(
            model_name='purchase_orders',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchase_orders',
            name='net_total',
        ),
        migrations.RemoveField(
            model_name='purchase_orders',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='purchase_orders',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='purchase_orders',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchase_orders',
            name='vendor',
        ),
        migrations.AddField(
            model_name='purchase_order_detail',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='purchase_orders',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase_orders',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase_orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('received', 'Received')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase_orders',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses'),
        ),
        migrations.AddField(
            model_name='request_note_detail',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.items'),
        ),
        migrations.AlterField(
            model_name='purchase_order_detail',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='stockmanagement',
        ),
    ]
