# Generated by Django 5.1.5 on 2025-05-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_stock_items_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_items',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_items', to='myapp.items'),
        ),
        migrations.AlterField(
            model_name='stock_items',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.stockmanagement'),
        ),
    ]
