# Generated by Django 5.1.5 on 2025-06-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_purchase_order_detail_discounted_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order_return',
            old_name='purchase_orders',
            new_name='purchase_order',
        ),
        migrations.AddField(
            model_name='purchase_orders',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vendors'),
        ),
    ]
