# Generated by Django 5.1.5 on 2025-05-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_stock_items_item_alter_stock_items_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_orders',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.area'),
        ),
    ]
