# Generated by Django 5.1.5 on 2025-06-12 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_purchase_orders_purchase_order_return_purchase_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'vendor_bill',
                'db_table': 'vendor_bill',
            },
        ),
        migrations.AlterField(
            model_name='purchase_orders',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='vendor_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vendor_bill')),
            ],
            options={
                'verbose_name_plural': 'vendor_payment',
                'db_table': 'vendor_payment',
            },
        ),
        migrations.CreateModel(
            name='vendor_transfer_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_transfer_note_no', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('intransit', 'Intransit'), ('delivered', 'Delivered')], default='dispatched', max_length=20)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase_orders')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vendors')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses')),
            ],
            options={
                'verbose_name_plural': 'vendor_transfer_note',
                'db_table': 'vendor_transfer_note',
            },
        ),
        migrations.AddField(
            model_name='vendor_bill',
            name='vendor_transfer_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vendor_transfer_note'),
        ),
        migrations.CreateModel(
            name='vendor_transfer_note_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_per_piece', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.items')),
                ('vendor_transfer_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vendor_transfer_note')),
            ],
            options={
                'verbose_name_plural': 'vendor_transfer_note_detail',
                'db_table': 'vendor_transfer_note_detail',
            },
        ),
        migrations.CreateModel(
            name='warehouse_receive_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receive_note_no', models.CharField(max_length=50, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('received', 'Received')], default='pending', max_length=50)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vendor_transfer_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vendor_transfer_note')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses')),
            ],
            options={
                'verbose_name_plural': 'warehouse_receive_note',
                'db_table': 'warehouse_receive_note',
            },
        ),
        migrations.CreateModel(
            name='warehouse_receive_note_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('warehouse_receive_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouse_receive_note')),
            ],
            options={
                'verbose_name_plural': 'warehouse_receive_note_detail',
                'db_table': 'warehouse_receive_note_detail',
            },
        ),
    ]
