# Generated by Django 5.1.5 on 2025-05-22 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_sales_orders_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_items',
            name='stock',
        ),
        migrations.AddField(
            model_name='notification',
            name='item_choices',
            field=models.CharField(choices=[('store', 'Store'), ('warehouse', 'Warehouse')], default='store', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.items'),
        ),
        migrations.AlterField(
            model_name='tax_configurations',
            name='applies_to',
            field=models.CharField(choices=[('Sales', 'sales'), ('Purchase', 'purchase'), ('Both', 'both')], default='sales', max_length=9),
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.TextField(blank=True, null=True)),
                ('store_location', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.warehouses')),
            ],
            options={
                'verbose_name_plural': 'store',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='request_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
            ],
        ),
        migrations.AddField(
            model_name='stock_items',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.store'),
        ),
        migrations.CreateModel(
            name='transfer_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_transferred', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('dispatched', ' Dispatched'), ('intransit', 'Intransit'), ('delivered', 'Delivered')], default='dispatched', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('request_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.request_note')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses')),
            ],
        ),
        migrations.CreateModel(
            name='receiver_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_received', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
                ('transfer_note_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.transfer_note')),
            ],
        ),
        migrations.CreateModel(
            name='warehouse_stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('safety_stock_level', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses')),
            ],
            options={
                'verbose_name_plural': 'warehouse_stock',
                'db_table': 'warehouse_stock',
            },
        ),
    ]
