# Generated by Django 5.1.5 on 2025-06-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_vendor_bill_alter_purchase_orders_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_payment',
            name='bill',
        ),
        migrations.DeleteModel(
            name='vendor_bill',
        ),
    ]
