# Generated by Django 5.1.5 on 2025-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_stock_items_stock_notification_item_choices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiver_note',
            options={'verbose_name_plural': 'receiver_note'},
        ),
        migrations.AlterModelOptions(
            name='request_note',
            options={'verbose_name_plural': 'request_note'},
        ),
        migrations.AlterModelOptions(
            name='transfer_note',
            options={'verbose_name_plural': 'transfer_note'},
        ),
        migrations.RenameField(
            model_name='receiver_note',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='request_note',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='transfer_note',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='warehouse_stock',
            old_name='item_id',
            new_name='item',
        ),
        migrations.AddField(
            model_name='request_note',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transfer_note',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='receiver_note',
            table='receiver_note',
        ),
        migrations.AlterModelTable(
            name='request_note',
            table='request_note',
        ),
        migrations.AlterModelTable(
            name='transfer_note',
            table='transfer_note',
        ),
    ]
