# Generated by Django 5.1.5 on 2025-05-22 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_receiver_note_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receiver_note',
            new_name='receive_note',
        ),
        migrations.AlterModelOptions(
            name='receive_note',
            options={'verbose_name_plural': 'receive_note'},
        ),
        migrations.AlterModelTable(
            name='receive_note',
            table='receive_note',
        ),
    ]
