# Generated by Django 5.1.5 on 2025-06-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_vendor_bill_vendor_payment_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_bill',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='vendor_bill',
            name='tax',
        ),
    ]
