# Generated by Django 5.1.5 on 2025-06-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_vendor_bill_discount_remove_vendor_bill_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_bill',
            name='paid_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_payment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
