# Generated by Django 5.1.5 on 2025-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_vendor_bill_paid_amount_alter_vendor_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('other', 'Other')], max_length=50),
        ),
    ]
