# Generated by Django 5.1.5 on 2025-06-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_vendor_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_bill',
            name='paid_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
