# Generated by Django 5.1.5 on 2025-06-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_vendor_bill_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_bill',
            name='paid_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
