# Generated by Django 5.1.5 on 2025-06-18 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_vendor_bill_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_adjustments',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.store'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='store_return_to_warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('inventory_adjustments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inventory_adjustments')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouses')),
            ],
        ),
    ]
