# Generated by Django 5.1.5 on 2025-06-18 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_inventory_adjustments_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_order_return',
            name='sales_order_detail',
        ),
        migrations.AddField(
            model_name='sales_order_return',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.store'),
            preserve_default=False,
        ),
    ]
