# Generated by Django 5.1.5 on 2025-06-19 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_sales_order_return_sales_order_detail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store_return_to_warehouse',
            options={'verbose_name_plural': 'sales_return_to_warehouse'},
        ),
        migrations.AlterModelTable(
            name='store_return_to_warehouse',
            table='store_return_to_warehouse',
        ),
        migrations.CreateModel(
            name='defective_stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inventory_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inventory_adjustments')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
            ],
            options={
                'verbose_name_plural': 'defective_stock',
                'db_table': 'defective_stock',
            },
        ),
    ]
