from django.contrib import admin
from .models import categories, sales_order_return,sales_order_return_detail, purchase_order_return_detail, sales_order_detail, purchase_order_return, area,purchase_order_detail, customers, discounts, inventory_adjustments, items, purchase_orders, purchase_receipts, User, sales_order_discounts, sales_orders, sales_order_tax,shipments, stock_items, stockmanagement, tax_configurations,  vendors, warehouses
admin.site.register(categories)
admin.site.register(customers)
admin.site.register(discounts)
admin.site.register(inventory_adjustments)
admin.site.register(items)
admin.site.register(purchase_orders)
admin.site.register(purchase_order_detail)
admin.site.register(purchase_order_return)
admin.site.register(purchase_order_return_detail)
admin.site.register(purchase_receipts)
admin.site.register(sales_order_discounts)
admin.site.register(sales_orders)
admin.site.register(sales_order_return)
admin.site.register(sales_order_tax)
admin.site.register(shipments)
admin.site.register(stockmanagement)
admin.site.register(tax_configurations)
admin.site.register(vendors)
admin.site.register(warehouses)
admin.site.register(stock_items)
# admin.site.register(User)
admin.site.register(area)
admin.site.register(sales_order_detail)
admin.site.register(sales_order_return_detail)